apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: netology-homework
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>cool</title>
    </head>
    <body>
      <h1>nice</h1>
    </body>
    </html>
